import Logo from "./components/Logo"

export const metadata = {
  title: 'Wild-Oasis Website',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <header>
        <Logo />
      </header>
      <body>{children}</body>
    </html>
  )
}
